import Head from 'next/head'
import Hero from '../components/Hero/Hero'
import Reference from '../components/Reference/Reference'
import TargetSection from '../components/TargetSection/TargetSection'
import ValueAndStandards from '../components/ValueAndStandards/ValueAndStandards'

export default function Home() {
  return (
    <div>
      <Head>
        <title>BNM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>

      <main>
        {/* ========= Hero ======== */}
        <Hero />

        {/* ========= Target Section ========= */}
        <hr />
        <TargetSection />

        {/* ========= Reference ========== */}
        <hr />
        <Reference />

        {/* ========= Value and Standards ========= */}

        <ValueAndStandards />
        
       </main>
    </div>
  )
}
