import Head from 'next/head'
import Hero from '../components/Hero/Hero'

export default function Home() {
  return (
    <div>
      <Head>
        <title>BNM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>

      <main>
        {/* ========= Hero ======== */}
        <Hero />
        <Hero />
         
       </main>
    </div>
  )
}
